USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Answer_GetAll
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Answer_GetById
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Branch_GetAll
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Branch_GetById
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Classroom_GetAll
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Classroom_GetById
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Department_GetAll
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Department_GetById
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Question_Add
TO GIANGVIEN;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Question_Delete
TO GIANGVIEN;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Question_Update
TO GIANGVIEN;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Question_GetAll
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Question_GetById
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Register_GetAll
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Register_GetById
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Student_GetAll
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Student_GetById
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Student_GetFromClass
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Subject_GetAll
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Subject_GetById
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Teacher_GetAll
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Teacher_GetById
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Transcript_GetAll
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Transcript_GetById
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Xem_Bang_Diem_Lop
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Xem_Bang_Diem_Sinh_Vien
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Xem_Danh_Sach_Dang_Ky
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Xem_Ket_Qua
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Xoa_Login
TO TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Tao_Login
TO TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_TaoDeThi
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Lay_Thong_Tin_Dang_Nhap
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_GET_REGISTER_LIST
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Classroom_Check
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Register_Check
TO GIANGVIEN, TRUONG;
GO

USE TN_CSDLPT
GRANT EXECUTE ON OBJECT::SP_Student_Check
TO GIANGVIEN, TRUONG;
GO