/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.ReportForms;

import dao.ClassroomDao;
import dao.SubjectDao;
import helper.JDBC_Connection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import model.Classroom;
import model.Subject;

/**
 *
 * @author Nguyen Hai Dang
 */
public class TranscriptReportFrame extends javax.swing.JFrame {

    List<Subject> _listSubject;
    List<Classroom> _listClassroom;

    /**
     * Creates new form TranscriptReportFrame
     */
    public TranscriptReportFrame() {
        initComponents();
        loadSubjectComboBox();
        loadClassComboBox();
    }

    private void loadSubjectComboBox() {
        SubjectDao subjectDAO = new SubjectDao();
        _listSubject = subjectDAO.getAllSubjects();
        for (Subject subject : _listSubject) {
            subjectComboBox.addItem(subject.getTenmh());
        }
    }

    private void loadClassComboBox() {
        ClassroomDao classDAO = new ClassroomDao();
        _listClassroom = classDAO.getAllClassrooms();
        for (Classroom classroom : _listClassroom) {
            classComboBox.addItem(classroom.getTenLop());
        }
    }

    private String convertMarkToString(double mark) {
        String result = "";
        int integer = (int)mark;
        double decimal = mark - integer;
        String slDecimal = String.valueOf(decimal).length() > 4? String.valueOf(decimal).substring(2,4) : String.valueOf(decimal).substring(2);
        String tmp[] = {String.valueOf(integer), slDecimal};
        for (int i = 0; i < tmp.length; i++) {
            int value = Integer.valueOf(tmp[i]);
            if(i==1 && value == 0)
                break;
            
            int oneDigit;
            boolean unitMode = false;
            boolean tenCase = false;
            
            if(i==1)
                result += "phẩy ";
            
            while (value >= 0) {
                if (i == 0) {
                    oneDigit = value;
                    value = -1;
                }
                else {
                    value = (int)(value % 10) == 0 ? (int)(value / 10) : value;

                    if (value > 9) {
                        oneDigit = (int)(value / 10);
                        value = (int)(value % 10);
                        unitMode = true;
                    }
                    else {
                        oneDigit = value;
                        value = -1;
                    }
                }

                switch (oneDigit) {
                    case 0: {
                        result += "không ";
                        break;
                    }
                    case 1: {
                        if(i == 1 && unitMode && value != -1)
                        {
                            tenCase = true;
                            result += "mười ";
                            break;
                        }
                        result += (i == 1 && unitMode && value == -1 && !tenCase) ? "mốt " : "một ";
                        break;
                    }
                    case 2: {
                        result += "hai ";
                        break;
                    }
                    case 3: {
                        result += "ba ";
                        break;
                    }
                    case 4: {
                        result += "bốn ";
                        break;
                    }
                    case 5: {
                        result += (i == 1 && unitMode && value == -1) ? "lăm " : "năm ";
                        break;
                    }
                    case 6: {
                        result += "sáu ";
                        break;
                    }
                    case 7: {
                        result += "bảy ";
                        break;
                    }
                    case 8: {
                        result += "tám ";
                        break;
                    }
                    case 9: {
                        result += "chín ";
                        break;
                    }
                    case 10: {
                        result += "mười ";
                    }
                    default:
                        break;
                }
                if(unitMode && value != -1 && !tenCase)
                    result += "mươi ";
            }
        }
        result = result.trim();
        result = result.substring(0, 1).toUpperCase() + result.substring(1);
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        classComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        subjectComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        examTimeComboBox = new javax.swing.JComboBox<>();
        viewReportButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Lớp");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Môn học");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Lần thi");

        examTimeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        viewReportButton.setText("Xem bảng điểm");
        viewReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReportButtonActionPerformed(evt);
            }
        });

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sinh viên", "Họ", "Tên", "Điểm", "Điểm chữ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(dataTable);
        if (dataTable.getColumnModel().getColumnCount() > 0) {
            dataTable.getColumnModel().getColumn(0).setResizable(false);
            dataTable.getColumnModel().getColumn(0).setPreferredWidth(70);
            dataTable.getColumnModel().getColumn(1).setResizable(false);
            dataTable.getColumnModel().getColumn(1).setPreferredWidth(150);
            dataTable.getColumnModel().getColumn(2).setResizable(false);
            dataTable.getColumnModel().getColumn(2).setPreferredWidth(70);
            dataTable.getColumnModel().getColumn(3).setResizable(false);
            dataTable.getColumnModel().getColumn(3).setPreferredWidth(70);
            dataTable.getColumnModel().getColumn(4).setResizable(false);
            dataTable.getColumnModel().getColumn(4).setPreferredWidth(200);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(classComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addComponent(subjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(examTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(viewReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(classComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(subjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(examTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(viewReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReportButtonActionPerformed
        String subjectID = _listSubject.get(subjectComboBox.getSelectedIndex()).getMamh();
        String classroomID = _listClassroom.get(classComboBox.getSelectedIndex()).getMaLop();
        int examTime = Integer.valueOf(examTimeComboBox.getSelectedItem().toString());

        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        model.setNumRows(0);

        Connection connector = JDBC_Connection.getPublisherConnection();
        String sql = "{call dbo.SP_Xem_Bang_Diem(?,?,?)}";

        try {
            PreparedStatement ps = connector.prepareStatement(sql);
            ps.setString(1, subjectID);
            ps.setString(2, classroomID);
            ps.setInt(3, examTime);

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector vt = new Vector();
                Double mark = rs.getDouble("DIEM");
                vt.add(rs.getString("MASV"));
                vt.add(rs.getString("HO"));
                vt.add(rs.getString("TEN"));   
                vt.add(mark);
                vt.add(convertMarkToString(mark));
                model.addRow(vt);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_viewReportButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TranscriptReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TranscriptReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TranscriptReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TranscriptReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TranscriptReportFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> classComboBox;
    private javax.swing.JTable dataTable;
    private javax.swing.JComboBox<String> examTimeComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> subjectComboBox;
    private javax.swing.JButton viewReportButton;
    // End of variables declaration//GEN-END:variables
}
