/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.QuestionForms;

import dao.QuestionDao;
import dao.SubjectDao;
import dao.TeacherDao;
import static java.lang.Integer.parseInt;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Question;
import model.Subject;
import model.Teacher;

/**
 *
 * @author Tozaff
 */
public class EditQuestionForm extends javax.swing.JFrame {

    /**
     * Creates new form AddQuestionForm
     */
    Question quest = new Question();
    QuestionDao questDao = new QuestionDao();
    SubjectDao MhDao = new SubjectDao();
    TeacherDao GvDao = new TeacherDao();

    public EditQuestionForm(int data) {

        initComponents();

        quest = questDao.getQuestionById(data);
        setInput();
        tf_CauHoi.setEnabled(false);
        setArlet(false);
        showSubject();
        showTeacher();
    }

    public EditQuestionForm() {
        initComponents();
        setArlet(false);
        showSubject();
        showTeacher();
    }

    private void getInput() {
        quest.setCauHoi(parseInt(tf_CauHoi.getText()));
        quest.setMamh(cbxMaMH.getSelectedItem().toString());
        quest.setTrinhDo(cb_TrinhDo.getSelectedItem().toString());
        quest.setNoiDung(txt_NoiDung.getText().trim());
        quest.setA(tf_A.getText().trim());
        quest.setB(tf_B.getText().trim());
        quest.setC(tf_C.getText().trim());
        quest.setD(tf_D.getText().trim());
        quest.setDapAn(cb_DapAn.getSelectedItem().toString());
        quest.setMagv(cbxMaMH.getSelectedItem().toString());
    }

    private void setInput() {
        tf_CauHoi.setText(String.valueOf(quest.getCauHoi()));
        cbxMaGV.setSelectedItem(quest.getMamh());
        cb_TrinhDo.setSelectedItem(quest.getTrinhDo());
        txt_NoiDung.setText(quest.getNoiDung());
        tf_A.setText(quest.getA());
        tf_B.setText(quest.getB());
        tf_C.setText(quest.getC());
        tf_D.setText(quest.getD());
        cb_DapAn.setSelectedItem(quest.getDapAn());
        cbxMaMH.setSelectedItem(quest.getMagv());
    }

    private void showSubject() {
        List<Subject> subjects = MhDao.getAllSubjects();

        for (Subject subject : subjects) {
            cbxMaMH.addItem(subject.getMamh());
        }
    }

    private void showTeacher() {
        List<Teacher> teachers = GvDao.getAllTeachers();

        for (Teacher teacher : teachers) {
            cbxMaGV.addItem(teacher.getMagv());
        }
    }

    public void setArlet(boolean shit) {
        arletCauHoi.setVisible(shit);
        arletNoiDung.setVisible(shit);
        arletA.setVisible(shit);
        arletB.setVisible(shit);
        arletC.setVisible(shit);
        arletD.setVisible(shit);

    }

    private void createAlert(JLabel label, String alertContent) {
        label.setText(alertContent);
        label.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_CauHoi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_A = new javax.swing.JTextField();
        tf_B = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_C = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_D = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_NoiDung = new javax.swing.JTextArea();
        cb_DapAn = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        cb_TrinhDo = new javax.swing.JComboBox();
        arletCauHoi = new javax.swing.JLabel();
        arletA = new javax.swing.JLabel();
        arletB = new javax.swing.JLabel();
        arletC = new javax.swing.JLabel();
        arletD = new javax.swing.JLabel();
        arletNoiDung = new javax.swing.JLabel();
        cbxMaMH = new javax.swing.JComboBox();
        cbxMaGV = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Sửa câu hỏi");

        jLabel3.setText("Câu hỏi số:");

        jLabel4.setText("Mã môn học:");

        jLabel6.setText("Trình độ:");

        jLabel7.setText("Nội dung:");

        jLabel8.setText("Lựa chọn A:");

        tf_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_AActionPerformed(evt);
            }
        });

        tf_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_BActionPerformed(evt);
            }
        });

        jLabel9.setText("Lựa chọn B:");

        jLabel10.setText("Lựa chọn C:");

        tf_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_CActionPerformed(evt);
            }
        });

        jLabel11.setText("Lựa chọn D:");

        tf_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_DActionPerformed(evt);
            }
        });

        jLabel12.setText("Đáp án đúng:");

        jLabel13.setText("Mã giáo viên:");

        txt_NoiDung.setColumns(20);
        txt_NoiDung.setRows(5);
        jScrollPane1.setViewportView(txt_NoiDung);

        jScrollPane2.setViewportView(jScrollPane1);

        cb_DapAn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_DapAn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D" }));

        jButton1.setText("Xác nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cb_TrinhDo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C" }));

        arletCauHoi.setForeground(new java.awt.Color(255, 0, 0));
        arletCauHoi.setText("Không bỏ trống Câu hỏi số");

        arletA.setForeground(new java.awt.Color(255, 0, 0));
        arletA.setText("Không bỏ trống Lựa chọn A");

        arletB.setForeground(new java.awt.Color(255, 0, 0));
        arletB.setText("Không bỏ trống Lựa chọn B");

        arletC.setForeground(new java.awt.Color(255, 0, 0));
        arletC.setText("Không bỏ trống Lựa chọn C");

        arletD.setForeground(new java.awt.Color(255, 0, 0));
        arletD.setText("Không bỏ trống Lựa chọn D");

        arletNoiDung.setForeground(new java.awt.Color(255, 0, 0));
        arletNoiDung.setText("Không bỏ trống Nội dung");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cb_DapAn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_C)
                                    .addComponent(tf_B)
                                    .addComponent(tf_A)
                                    .addComponent(tf_CauHoi)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addComponent(tf_D)
                                    .addComponent(cb_TrinhDo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxMaMH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxMaGV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(arletCauHoi)
                                    .addComponent(arletA)
                                    .addComponent(arletB)
                                    .addComponent(arletC)
                                    .addComponent(arletD)
                                    .addComponent(arletNoiDung)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(jButton1)))))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_CauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(arletCauHoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb_TrinhDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(arletNoiDung)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(arletA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(arletB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(arletC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(arletD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cb_DapAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cbxMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_AActionPerformed

    private void tf_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_BActionPerformed

    private void tf_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_CActionPerformed

    private void tf_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_DActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            boolean check = true;
            //reset arlet 
            setArlet(false);

            //set arlet 
            //2
            if (tf_CauHoi.getText().trim().length() == 0) {
                createAlert(arletNoiDung, "Không để trống Nội dung");
                check = false;
            }
            //3
            if (tf_A.getText().trim().length() == 0) {
                createAlert(arletA, "Không để trống Lựa chọn A");
                check = false;
            }
            //4
            if (tf_B.getText().trim().length() == 0) {
                createAlert(arletB, "Không để trống Lựa chọn B");
                check = false;
            }
            //5
            if (tf_C.getText().trim().length() == 0) {
                createAlert(arletC, "Không để trống Lựa chọn C");
                check = false;
            }
            //6
            if (tf_D.getText().trim().length() == 0) {
                createAlert(arletD, "Không để trống Lựa chọn D");
                check = false;
            }
            //safe now, i will get input without care
            if (check == true) {
                getInput();
            }

            //after the check
            if (check) {
                if (questDao.addQuestion(quest)) {
                    JOptionPane.showMessageDialog(rootPane, "Sửa thành công!");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Sửa thất bại!");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Sửa thất bại!");
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditQuestionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditQuestionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditQuestionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditQuestionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditQuestionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arletA;
    private javax.swing.JLabel arletB;
    private javax.swing.JLabel arletC;
    private javax.swing.JLabel arletCauHoi;
    private javax.swing.JLabel arletD;
    private javax.swing.JLabel arletNoiDung;
    private javax.swing.JComboBox cb_DapAn;
    private javax.swing.JComboBox cb_TrinhDo;
    private javax.swing.JComboBox cbxMaGV;
    private javax.swing.JComboBox cbxMaMH;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tf_A;
    private javax.swing.JTextField tf_B;
    private javax.swing.JTextField tf_C;
    private javax.swing.JTextField tf_CauHoi;
    private javax.swing.JTextField tf_D;
    private javax.swing.JTextArea txt_NoiDung;
    // End of variables declaration//GEN-END:variables
}
