/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.TeacherForms;

import dao.DepartmentDao;
import dao.TeacherDao;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.Department;
import model.Teacher;

/**
 *
 * @author Tozaff
 */
public class AddTeacherForm extends javax.swing.JFrame {

    /**
     * Creates new form AddTeacherForm
     */
    Teacher gv = new Teacher();
    TeacherDao gvDao = new TeacherDao();
    DepartmentDao khoaDao = new DepartmentDao();
    //regex
    String reTiengViet = "[aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ\\s]";
    String reTiengViet2 = "[a-zA-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂưăạảấầẩẫậắằẳẵặẹẻẽềềểỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ\\s]";

    public AddTeacherForm() {
        initComponents();
        setArlet(false);
        showDepart();
    }

    private void showDepart() {
        List<Department> departs = khoaDao.getAllDepartments();

        for (Department depart : departs) {
            cbxKhoa.addItem(depart.getMakh());
        }

    }

    public void setArlet(boolean shit) {
        arletMaGV.setVisible(shit);
        arletHo.setVisible(shit);
        arletTen.setVisible(shit);
        arletHocVi.setVisible(shit);
        arletMaKhoa.setVisible(shit);
    }

    private void createAlert(JLabel label, String alertContent) {
        label.setText(alertContent);
        label.setVisible(true);
    }

    private void getInput() {
        gv.setMagv(tf_MaGV.getText().trim());
        gv.setHo(tf_Ho.getText().trim());
        gv.setTen(tf_Ten.getText().trim());
        gv.setHocVi(tf_HocVi.getText().trim());
        gv.setMakh(cbxKhoa.getSelectedItem().toString().trim());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_MaGV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_Ho = new javax.swing.JTextField();
        tf_Ten = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_HocVi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        arletMaGV = new javax.swing.JLabel();
        arletHo = new javax.swing.JLabel();
        arletTen = new javax.swing.JLabel();
        arletHocVi = new javax.swing.JLabel();
        arletMaKhoa = new javax.swing.JLabel();
        cbxKhoa = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Thêm Giáo Viên");

        jLabel2.setText("Mã giáo viên:");

        jLabel3.setText("Họ:");

        jLabel4.setText("Tên:");

        jLabel5.setText("Học vị:");

        jLabel6.setText("Mã khoa:");

        jButton1.setText("Xác nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        arletMaGV.setForeground(new java.awt.Color(255, 0, 0));
        arletMaGV.setText("Không bỏ trống Mã giáo viên");

        arletHo.setForeground(new java.awt.Color(255, 0, 0));
        arletHo.setText("Không bỏ trống Họ");

        arletTen.setForeground(new java.awt.Color(255, 0, 0));
        arletTen.setText("Không bỏ trống Tên");

        arletHocVi.setForeground(new java.awt.Color(255, 0, 0));
        arletHocVi.setText("Không bỏ trống Học vị");

        arletMaKhoa.setForeground(new java.awt.Color(255, 0, 0));
        arletMaKhoa.setText("Không bỏ trống Mã khoa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_MaGV, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_Ho, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_Ten, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_HocVi, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(cbxKhoa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arletMaGV)
                            .addComponent(arletHo)
                            .addComponent(arletTen)
                            .addComponent(arletHocVi)
                            .addComponent(arletMaKhoa)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jButton1)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_MaGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arletMaGV))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_Ho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arletHo))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_Ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arletTen))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_HocVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arletHocVi))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(arletMaKhoa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            getInput();
            boolean check = true;
            //reset arlet 
            setArlet(false);

            //set arlet 
            //1
            if (gv.getMagv().length() == 0) {
                createAlert(arletMaGV, "Không bỏ trống Mã giáo viên");
                check = false;
            } else if (gv.getMagv().matches("\\w{1,8}") == false) {
                createAlert(arletMaGV, "Tối đa 8 chữ cái không dấu hoặc số");
                check = false;
            } else if(gvDao.checkTeacher(gv.getMagv())==1)
            {
                createAlert(arletMaGV, "Mã giáo viên này đã tồn tại");
                check = false;
            }
            //2

            if (gv.getHo().length() == 0) {
                createAlert(arletHo, "Không bỏ trống Họ");
                check = false;
            } else if (gv.getHo().matches(reTiengViet + "+") == false) {
                createAlert(arletHo, "Vui lòng sử dụng chữ cái Tiếng Việt");
                check = false;
            } else if (gv.getHo().matches(reTiengViet + "{1,40}") == false) {
                createAlert(arletHo, "Tối đa 40 kí tự");
                check = false;
            }
            //3

            if (gv.getTen().length() == 0) {
                createAlert(arletTen, "Không bỏ trống Tên");
                check = false;
            } else if (gv.getTen().matches(reTiengViet + "+") == false) {
                createAlert(arletTen, "Vui lòng sử dụng chữ cái Tiếng Việt");
                check = false;
            } else if (gv.getTen().matches(reTiengViet + "{1,40}") == false) {
                createAlert(arletTen, "Tối đa 40 kí tự");
                check = false;
            }
            //4

            if (gv.getHocVi().length() == 0) {
                createAlert(arletHocVi, "Không bỏ trống Học vị");
                check = false;
            } else if (gv.getHocVi().matches(".{1,40}") == false) {
                createAlert(arletHocVi, "Tối đa 40 kí tự");
                check = false;
            }
            //5

            if (gv.getMakh().length() == 0) {
                createAlert(arletMaKhoa, "Không bỏ trống Mã khoa");
                check = false;
            }

            //after the check
            if (check) {
                if (gvDao.addTeacher(gv)) {
                    JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Thêm thất bại");
                }
            }

        } catch (Exception e) {
            System.out.println(e.toString());
            JOptionPane.showMessageDialog(rootPane, "Thêm thất bại");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTeacherForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTeacherForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTeacherForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTeacherForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTeacherForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arletHo;
    private javax.swing.JLabel arletHocVi;
    private javax.swing.JLabel arletMaGV;
    private javax.swing.JLabel arletMaKhoa;
    private javax.swing.JLabel arletTen;
    private javax.swing.JComboBox cbxKhoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tf_Ho;
    private javax.swing.JTextField tf_HocVi;
    private javax.swing.JTextField tf_MaGV;
    private javax.swing.JTextField tf_Ten;
    // End of variables declaration//GEN-END:variables
}
