/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.RegisterForms;

import dao.ClassroomDao;
import dao.RegisterDao;
import dao.SubjectDao;
import dao.TeacherDao;
import helper.DateHelper;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.Classroom;
import model.Register;
import model.Subject;
import model.Teacher;

/**
 *
 * @author Tozaff
 */
public class AddRegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form AddRegisterForm
     */
    Register dky = new Register();
    RegisterDao dky_dao = new RegisterDao();
    ClassroomDao classroomDao;
    SubjectDao MhDao = new SubjectDao();
    TeacherDao GvDao = new TeacherDao();

    public AddRegisterForm() {
        initComponents();
        setArlet(false);
        showClassroom();
        showSubject();
        showTeacher();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void getInput() {
        dky.setMagv(cbxMaGV.getSelectedItem().toString());
        dky.setMamh(cbxMaMH.getSelectedItem().toString());
        dky.setMalop(cbxClassroom.getSelectedItem().toString());
        dky.setTrinhDo(cb_TrinhDo.getSelectedItem().toString());
        dky.setNgayThi(DateHelper.toString(tf_NgayThi.getDate()));
        dky.setLan(Integer.parseInt(cb_Lan.getSelectedItem().toString()));
        dky.setSoCauThi(Integer.parseInt(tf_SoCauThi.getText()));
        dky.setThoiGian(Integer.parseInt(tf_ThoiGian.getText()));
    }

    private void showClassroom() {
        classroomDao = new ClassroomDao();
        List<Classroom> classrooms = classroomDao.getAllClassrooms();

        for (Classroom classroom : classrooms) {
            cbxClassroom.addItem(classroom.getMaLop());
        }
    }

    private void showSubject() {
        List<Subject> subjects = MhDao.getAllSubjects();

        for (Subject subject : subjects) {
            cbxMaMH.addItem(subject.getMamh());
        }
    }

    private void showTeacher() {
        List<Teacher> teachers = GvDao.getAllTeachers();

        for (Teacher teacher : teachers) {
            cbxMaGV.addItem(teacher.getMagv());
        }
    }

    public void setArlet(boolean shit) {
        arletSoCauThi.setVisible(shit);
        arletThoiGian.setVisible(shit);
    }

    private void createAlert(JLabel label, String alertContent) {
        label.setText(alertContent);
        label.setVisible(true);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_ThoiGian = new javax.swing.JTextField();
        tf_SoCauThi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cb_TrinhDo = new javax.swing.JComboBox();
        cb_Lan = new javax.swing.JComboBox();
        tf_NgayThi = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        arletSoCauThi = new javax.swing.JLabel();
        arletThoiGian = new javax.swing.JLabel();
        cbxClassroom = new javax.swing.JComboBox();
        cbxMaMH = new javax.swing.JComboBox();
        cbxMaGV = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Thêm Đăng Ký");

        jLabel3.setText("Mã giáo viên:");

        jLabel4.setText("Mã môn học:");

        jLabel5.setText("Lần:");

        jLabel6.setText("Mã lớp:");

        jLabel7.setText("Trình độ:");

        jLabel8.setText("Ngày thi");

        jLabel9.setText("Số câu thi:");

        jLabel10.setText("Thời gian:");

        cb_TrinhDo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C" }));

        cb_Lan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));

        tf_NgayThi.setDateFormatString("dd/MM/yyyy");

        jButton1.setText("Xác nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        arletSoCauThi.setForeground(new java.awt.Color(255, 0, 0));
        arletSoCauThi.setText("Không bỏ trống Số câu thi");

        arletThoiGian.setForeground(new java.awt.Color(255, 0, 0));
        arletThoiGian.setText("Không bỏ trống Thời gian");

        jLabel11.setText("Đơn vị: phút");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(tf_SoCauThi, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxClassroom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxMaMH, 0, 240, Short.MAX_VALUE)
                                    .addComponent(cb_TrinhDo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_NgayThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cb_Lan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(tf_ThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arletSoCauThi)
                            .addComponent(arletThoiGian)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jButton1)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbxMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbxMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cbxClassroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cb_TrinhDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(tf_NgayThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cb_Lan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_SoCauThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arletSoCauThi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_ThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arletThoiGian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {

            boolean check = true;
            //reset arlet 
            setArlet(false);

            //set arlet 
            //1
            if (tf_SoCauThi.getText().trim().length() == 0) {
                createAlert(arletSoCauThi, "Không bỏ trống Số câu thi");
                check = false;
            } else if (tf_SoCauThi.getText().trim().matches("\\d+") == false) {
                createAlert(arletSoCauThi, "Chỉ nhập số nguyên");
                check = false;
            }
            //2
            if (tf_ThoiGian.getText().trim().length() == 0) {
                createAlert(arletThoiGian, "Không bỏ trống Thời gian");
                check = false;
            } else if (tf_ThoiGian.getText().trim().matches("\\d+") == false) {
                createAlert(arletThoiGian, "Chỉ nhập số nguyên");
                check = false;
            }
            //get the input
            if (check == true) {
                getInput();
            }
            //recheck value of int
            //1
            if (dky.getSoCauThi() < 10 || dky.getSoCauThi() > 100) {
                if (check) {
                    createAlert(arletSoCauThi, "Chỉ nhận giá trị trong khoảng [10,100]");
                    check = false;
                }
            }
            //2
            if (dky.getThoiGian() < 10 || dky.getThoiGian() > 100) {
                if (check) {
                    createAlert(arletThoiGian, "Chỉ nhận giá trị trong khoảng [15,60]");
                    check = false;
                }
            }
            if (check == true)
            {
                if(dky_dao.checkRegister(dky.getMamh(), dky.getMalop(), dky.getLan())==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "Đăng ký này đã tồn tại");
                    check = false;
                }
            }
            //after the check
            if (check == true) {
                if (dky_dao.addRegister(dky)) {
                    JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Thêm thất bại");
                }
            }

        } catch (Exception e) {
            System.out.println(e.toString());
            JOptionPane.showMessageDialog(rootPane, "Thêm thất bại");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arletSoCauThi;
    private javax.swing.JLabel arletThoiGian;
    private javax.swing.JComboBox cb_Lan;
    private javax.swing.JComboBox cb_TrinhDo;
    private javax.swing.JComboBox cbxClassroom;
    private javax.swing.JComboBox cbxMaGV;
    private javax.swing.JComboBox cbxMaMH;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser tf_NgayThi;
    private javax.swing.JTextField tf_SoCauThi;
    private javax.swing.JTextField tf_ThoiGian;
    // End of variables declaration//GEN-END:variables
}
