/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.RegisterForms;

import dao.ClassroomDao;
import dao.RegisterDao;
import dao.SubjectDao;
import dao.TeacherDao;
import helper.DateHelper;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.Classroom;
import model.Register;
import model.Subject;
import model.Teacher;

/**
 *
 * @author Tozaff
 */
public class EditRegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form AddRegisterForm
     */
    Register dky = new Register();
    RegisterDao dky_dao = new RegisterDao();
    ClassroomDao classroomDao;
    SubjectDao MhDao = new SubjectDao();
    TeacherDao GvDao = new TeacherDao();

    public EditRegisterForm() {
        initComponents();
        setArlet(false);
        showClassroom();
        showSubject();
        showTeacher();
    }

    public EditRegisterForm(String s1, String s2, int x) {
        initComponents();

        dky = dky_dao.getRegisterById(s1, s2, x);
        setInput();

        cbxMaMH.setEnabled(false);
        cbxClassroom.setEnabled(false);
        cb_Lan.setEnabled(false);
        setArlet(false);
        showTeacher();

    }

    public void setArlet(boolean shit) {
        arletSoCauThi.setVisible(shit);
        arletThoiGian.setVisible(shit);
    }

    private void createAlert(JLabel label, String alertContent) {
        label.setText(alertContent);
        label.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     private void getInput() {
        dky.setMagv(cbxMaGV.getSelectedItem().toString());
        dky.setMamh(cbxClassroom.getSelectedItem().toString());
        dky.setMalop(cbxMaMH.getSelectedItem().toString());
        dky.setTrinhDo(cb_TrinhDo.getSelectedItem().toString());
        dky.setNgayThi(DateHelper.toString(tf_NgayThi.getDate()));
        dky.setLan(Integer.parseInt(cb_Lan.getSelectedItem().toString()));
        dky.setSoCauThi(Integer.parseInt(tf_SoCauThi.getText()));
        dky.setThoiGian(Integer.parseInt(tf_ThoiGian.getText()));
    }

    private void setInput() {
        cbxMaGV.setSelectedItem(dky.getMagv());
        cbxMaMH.setSelectedItem(dky.getMamh());
        cbxClassroom.setSelectedItem(dky.getMalop());
        cb_TrinhDo.setSelectedItem(dky.getTrinhDo());
        tf_NgayThi.setDate(DateHelper.toDate(dky.getNgayThi()));
        cb_Lan.setSelectedItem(dky.getLan());
        tf_SoCauThi.setText(String.valueOf(dky.getSoCauThi()));
        tf_ThoiGian.setText(String.valueOf(dky.getThoiGian()));

    }
    private void showClassroom() {
        classroomDao = new ClassroomDao();
        List<Classroom> classrooms = classroomDao.getAllClassrooms();

        for (Classroom classroom : classrooms) {
            cbxClassroom.addItem(classroom.getMaLop());
        }
    }

    private void showSubject() {
        List<Subject> subjects = MhDao.getAllSubjects();

        for (Subject subject : subjects) {
            cbxMaMH.addItem(subject.getMamh());
        }
    }

    private void showTeacher() {
        List<Teacher> teachers = GvDao.getAllTeachers();

        for (Teacher teacher : teachers) {
            cbxMaGV.addItem(teacher.getMagv());
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_ThoiGian = new javax.swing.JTextField();
        tf_SoCauThi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cb_TrinhDo = new javax.swing.JComboBox();
        cb_Lan = new javax.swing.JComboBox();
        tf_NgayThi = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        arletSoCauThi = new javax.swing.JLabel();
        arletThoiGian = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbxMaGV = new javax.swing.JComboBox();
        cbxMaMH = new javax.swing.JComboBox();
        cbxClassroom = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Sửa Đăng Ký");

        jLabel3.setText("Mã giáo viên:");

        jLabel4.setText("Mã môn học:");

        jLabel5.setText("Lần:");

        jLabel6.setText("Mã lớp:");

        jLabel7.setText("Trình độ:");

        jLabel8.setText("Ngày thi");

        jLabel9.setText("Số câu thi:");

        jLabel10.setText("Thời gian:");

        cb_TrinhDo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C" }));

        cb_Lan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));

        tf_NgayThi.setDateFormatString("MM/dd/yyyy");

        jButton1.setText("Xác nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        arletSoCauThi.setForeground(new java.awt.Color(255, 0, 0));
        arletSoCauThi.setText("Không bỏ trống Số câu thi");

        arletThoiGian.setForeground(new java.awt.Color(255, 0, 0));
        arletThoiGian.setText("Không bỏ trống Thời gian");

        jLabel11.setText("Đơn vị: phút");

        cbxMaMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMaMHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel11)
                                                .addGap(188, 188, 188))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cb_Lan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tf_NgayThi, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tf_SoCauThi, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tf_ThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cb_TrinhDo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxMaMH, 0, 240, Short.MAX_VALUE)
                                            .addComponent(cbxClassroom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(arletSoCauThi)
                                    .addComponent(arletThoiGian)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cbxMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbxMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbxMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cbxClassroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cb_TrinhDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(tf_NgayThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cb_Lan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_SoCauThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arletSoCauThi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_ThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arletThoiGian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            boolean check = true;
            //reset arlet 
            setArlet(false);

            //set arlet 
            //1
            if (tf_SoCauThi.getText().trim() == null) {
                createAlert(arletSoCauThi, "Không bỏ trống Số câu thi");
                check = false;
            } else if (tf_SoCauThi.getText().trim().matches("\\d+")) {
                createAlert(arletSoCauThi, "Chỉ nhập số");
                check = false;
            }
            //2
            if (tf_ThoiGian.getText().trim() == null) {
                createAlert(arletThoiGian, "Không bỏ trống Thời gian");
                check = false;
            } else if (tf_ThoiGian.getText().trim().matches("\\d+")) {
                createAlert(arletThoiGian, "Chỉ nhập số");
                check = false;
            }
            //get the input
            getInput();
            //recheck value of int
            //1
            if (dky.getSoCauThi() < 10 && dky.getSoCauThi() > 100) {
                createAlert(arletSoCauThi, "Chỉ nhận giá trị trong khoảng [10,100]");
                check = false;
            }
            //2
            if (dky.getThoiGian() < 10 && dky.getThoiGian() > 100) {
                createAlert(arletThoiGian, "Chỉ nhận giá trị trong khoảng [15,60]");
                check = false;
            }
            //after the check
            if (check) {
                dky_dao.updateRegister(dky);
                JOptionPane.showMessageDialog(rootPane, "Sửa thành công");
            }
        } catch (Exception e) {
            System.out.println(e.toString());
            JOptionPane.showMessageDialog(rootPane, "Sửa thất bại");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbxMaMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMaMHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMaMHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditRegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arletSoCauThi;
    private javax.swing.JLabel arletThoiGian;
    private javax.swing.JComboBox cb_Lan;
    private javax.swing.JComboBox cb_TrinhDo;
    private javax.swing.JComboBox cbxClassroom;
    private javax.swing.JComboBox cbxMaGV;
    private javax.swing.JComboBox cbxMaMH;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser tf_NgayThi;
    private javax.swing.JTextField tf_SoCauThi;
    private javax.swing.JTextField tf_ThoiGian;
    // End of variables declaration//GEN-END:variables
}
