/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.StudentForms;

import dao.ClassroomDao;
import dao.StudentDao;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import helper.DateHelper;
import java.time.LocalDateTime;
import java.util.Date;
import model.Student;
import helper.DateHelper;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.Classroom;

/**
 *
 * @author Tozaff
 */
public class EditStudentForm extends javax.swing.JFrame {

    /**
     * Creates new form AddStudentForm
     */
    Student st1 = new Student();
    StudentDao Sdao = new StudentDao();
    ClassroomDao classroomDao;
    String reTiengViet = "[aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ\\s]";

    public EditStudentForm() {
        initComponents();
        txtMasv.setText(ListStudentFrame.maSV);
        showClassroom();
    }

    public EditStudentForm(String data) {

        initComponents();

        st1 = Sdao.getStudentById(data);
        setInput(st1);
        txtMasv.setText(data);
        txtMasv.setEnabled(false);

        showClassroom();

    }

    private void showClassroom() {
        classroomDao = new ClassroomDao();
        List<Classroom> classrooms = classroomDao.getAllClassrooms();
        for (Classroom classroom : classrooms) {
            cbxClassroom.addItem(classroom.getMaLop());
        }
    }

    private void resetF1() {
        txtMasv.setText("");
        txtHo.setText("");
        txtTen.setText("");
        txtNgaySinh.setDate(null);
        txtDiaChi.setText("");
        txtMatkhau.setText("");

    }

    private void getInput() {
        st1.setMasv(txtMasv.getText().trim());
        st1.setHo(txtHo.getText().trim());
        st1.setTen(txtTen.getText().trim());
        st1.setNgaySinh(DateHelper.toString(txtNgaySinh.getDate()));
        st1.setDiaChi(txtDiaChi.getText().trim());
        st1.setMaLop(cbxClassroom.getSelectedItem().toString());
        st1.setMatKhau(txtMatkhau.getPassword().toString().trim());

    }

    private void setInput(Student st) {
        txtMasv.setText(st.getMasv());
        txtHo.setText(st.getHo());
        txtTen.setText(st.getTen());
        txtNgaySinh.setDate(DateHelper.toDate(st.getNgaySinh()));
        txtDiaChi.setText(st.getDiaChi());
        cbxClassroom.setSelectedItem(st.getMaLop());
        txtMatkhau.setText(st.getMatKhau());
    }

    private void createAlert(JLabel label, String alertContent) {
        label.setText(alertContent);
        label.setVisible(true);
    }

    public void setArlet(boolean shit) {
        arletHo.setVisible(shit);
        arletTen.setVisible(shit);
        arletDiaChi.setVisible(shit);
        arletMaLop.setVisible(shit);
        arletMatKhau.setVisible(shit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDiaChi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMatkhau = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMasv = new javax.swing.JTextField();
        txtHo = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNgaySinh = new com.toedter.calendar.JDateChooser();
        cbxClassroom = new javax.swing.JComboBox();
        arletHo = new javax.swing.JLabel();
        arletTen = new javax.swing.JLabel();
        arletMaLop = new javax.swing.JLabel();
        arletMatKhau = new javax.swing.JLabel();
        arletDiaChi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã sinh viên:");

        jLabel8.setText("Mật khẩu:");

        jLabel3.setText("Họ:");

        jLabel4.setText("Tên:");

        jLabel5.setText("Ngày sinh:");

        jLabel6.setText("Địa chỉ:");

        jLabel7.setText("Mã lớp:");

        jButton1.setText("Xác nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Sửa Sinh Viên");

        jLabel9.setText("mm/dd/yyyy");

        txtNgaySinh.setDateFormatString("MM/dd/yyyy");

        arletHo.setForeground(new java.awt.Color(255, 0, 0));
        arletHo.setText("Không bỏ trống Họ");

        arletTen.setForeground(new java.awt.Color(255, 0, 0));
        arletTen.setText("Không bỏ trống Tên");

        arletMaLop.setForeground(new java.awt.Color(255, 0, 0));
        arletMaLop.setText("Không bỏ trống Mã lớp");

        arletMatKhau.setForeground(new java.awt.Color(255, 0, 0));
        arletMatKhau.setText("Không bỏ trống Mật khẩu");

        arletDiaChi.setForeground(new java.awt.Color(255, 0, 0));
        arletDiaChi.setText("Không bỏ trống Địa chỉ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8))
                                    .addGap(33, 33, 33)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtMatkhau)
                                        .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cbxClassroom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addGap(65, 65, 65)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9)
                                    .addComponent(txtMasv)
                                    .addComponent(txtHo)
                                    .addComponent(txtTen)
                                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arletHo)
                            .addComponent(arletTen)
                            .addComponent(arletMatKhau)
                            .addComponent(arletMaLop)
                            .addComponent(arletDiaChi))))
                .addGap(42, 131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMasv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arletHo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arletTen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arletDiaChi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbxClassroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arletMaLop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(arletMatKhau)))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            getInput();
            boolean check = true;
            //reset arlet 
            setArlet(false);
            
            //set arlet
            //2
            if (st1.getHo().length() == 0) {
                createAlert(arletHo, "Không bỏ trống Họ");
                check = false;
            } else if (st1.getHo().matches(reTiengViet + "+")) {
                createAlert(arletHo, "Chỉ sử dụng bảng chữ cái Tiếng Việt");
                check = false;
            } else if (st1.getHo().matches(reTiengViet + "{1,40}") == false) {
                createAlert(arletHo, "Tối đa 40 kí tự");
                check = false;
            }
            //3
            if (st1.getTen().length() == 0) {
                createAlert(arletTen, "Không bỏ trống Tên");
                check = false;
            } else if (st1.getTen().matches(reTiengViet + "+") == false) {
                createAlert(arletTen, "Chỉ sử dụng bảng chữ cái Tiếng Việt");
                check = false;
            } else if (st1.getTen().matches(reTiengViet + "{1,10}") == false) {
                createAlert(arletTen, "Tối đa 10 kí tự");
                check = false;
            }
            //4
            if (st1.getDiaChi().length() == 0) {
                createAlert(arletDiaChi, "Không bỏ trống Địa chỉ");
                check = false;
            } else if (st1.getDiaChi().matches(".{1,40}") == false) {
                createAlert(arletDiaChi, "Tối đa 40 kí tự");
                check = false;
            }
            //5
            if (st1.getMatKhau().length() == 0) {
                createAlert(arletMatKhau, "Không bỏ trống Mật khẩu");
                check = false;
            } else if (st1.getMatKhau().matches(".{1,20}") == false) {
                createAlert(arletMatKhau, "Tối đa 20 kí tự");
                check = false;
            }

            //after the check
            if (check) {
                Sdao.updateStudent(st1);
                JOptionPane.showMessageDialog(rootPane, "Sửa thành công");
            }

        } catch (Exception e) {
            System.out.println(e.toString());
            JOptionPane.showMessageDialog(rootPane, "Sửa thất bại");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditStudentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arletDiaChi;
    private javax.swing.JLabel arletHo;
    private javax.swing.JLabel arletMaLop;
    private javax.swing.JLabel arletMatKhau;
    private javax.swing.JLabel arletTen;
    private javax.swing.JComboBox cbxClassroom;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHo;
    private javax.swing.JTextField txtMasv;
    private javax.swing.JPasswordField txtMatkhau;
    private com.toedter.calendar.JDateChooser txtNgaySinh;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
